import { doc, setDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../config/firebase';

export const INITIAL_KB_CONTENT: Array<{
  id: string;
  url: string;
  title: string;
  content: string;
  tokens: string[];
}> = [
  { id: 'home', url: '/', title: 'Home - Wasilah', content: 'Wasilah is a community service organization dedicated to creating positive change through education, healthcare, environmental initiatives, and community development projects. We believe in empowering communities and creating sustainable impact through volunteer-driven programs. Our mission is to connect people who want to make a difference with opportunities that create lasting change.', tokens: ['wasilah','community','service','organization','education','healthcare','environmental','initiatives','development','projects','empowering','communities','sustainable','impact','volunteer','programs','mission','connect','people','difference','opportunities','change'] },
  { id: 'about', url: '/about', title: 'About Us - Wasilah', content: 'Wasilah was founded with a vision to bridge communities and create meaningful impact through collaborative service. We work across multiple sectors including education, healthcare, environmental conservation, and community development. Our team comprises dedicated volunteers, community leaders, and professionals who share a common goal: creating sustainable positive change in communities across Pakistan. We operate with transparency, accountability, and a deep commitment to serving those in need.', tokens: ['wasilah','founded','vision','bridge','communities','meaningful','impact','collaborative','service','sectors','education','healthcare','environmental','conservation','community','development','team','volunteers','leaders','professionals','goal','sustainable','change','pakistan','transparency','accountability','commitment','serving'] },
  { id: 'projects', url: '/projects', title: 'Projects - Wasilah', content: 'Our projects span multiple areas of community impact. Education Programs: We provide tutoring, scholarship support, and educational resources to underprivileged students. Healthcare Initiatives: Free medical camps, health awareness campaigns, and preventive care programs. Environmental Conservation: Tree planting drives, beach cleanups, and sustainability workshops. Community Development: Infrastructure projects, skills training, and livelihood support programs. Each project is designed with community input and measured for sustainable impact.', tokens: ['projects','community','impact','education','programs','tutoring','scholarship','support','resources','students','healthcare','initiatives','medical','camps','health','awareness','campaigns','preventive','care','environmental','conservation','tree','planting','beach','cleanups','sustainability','workshops','development','infrastructure','skills','training','livelihood','designed','measured','sustainable'] },
  { id: 'volunteer', url: '/volunteer', title: 'Volunteer - Wasilah', content: 'Join us as a volunteer and make a real difference in your community. We welcome volunteers aged 16 and above (parental consent required for minors). No prior experience necessary - we provide orientation and training. Volunteer opportunities include: event coordination, tutoring, healthcare support, environmental activities, administrative help, and social media management. You can volunteer once a month or multiple times per week based on your availability. After 20 hours of service, you will receive a volunteer certificate. Apply through our volunteer form and we will contact you within 3-5 business days.', tokens: ['volunteer','join','difference','community','welcome','aged','experience','orientation','training','opportunities','event','coordination','tutoring','healthcare','support','environmental','activities','administrative','social','media','management','availability','hours','service','certificate','apply','form','contact','business','days'] },
  { id: 'events', url: '/events', title: 'Events - Wasilah', content: 'We organize regular community events to engage volunteers and create impact. Upcoming events include health fairs with free medical checkups, educational workshops for skills development, tree planting drives for environmental conservation, and community gatherings for cultural exchange. Most events are free to attend and open to the public. Check our events calendar for schedules and registration details. We typically host 2-3 events per month across Karachi, Lahore, and Islamabad. Follow us on social media for event updates and photos.', tokens: ['events','organize','community','engage','volunteers','impact','health','fairs','medical','checkups','educational','workshops','skills','development','tree','planting','environmental','conservation','gatherings','cultural','exchange','free','attend','public','calendar','schedules','registration','details','month','karachi','lahore','islamabad','social','media','updates','photos'] },
  { id: 'contact', url: '/contact', title: 'Contact - Wasilah', content: 'Get in touch with us! We have offices in three major cities. Karachi Office: Main Office Complex, Clifton Block 5. Lahore Office: Model Town Extension. Islamabad Office: Blue Area Sector F-6. Email: info@wasilah.org. You can also reach us through this chat widget for quick questions. Our team responds to emails within 24 hours during business days. Follow us on Facebook, Instagram, and Twitter for updates and stories.', tokens: ['contact','touch','offices','cities','karachi','office','complex','clifton','lahore','model','town','islamabad','blue','area','sector','email','info','wasilah','reach','chat','widget','questions','team','responds','hours','business','days','facebook','instagram','twitter','updates','stories'] },
  { id: 'join-us', url: '/volunteer', title: 'How to Join Us', content: 'To join Wasilah as a volunteer, follow these simple steps: 1) Visit the Volunteer page on our website 2) Complete the application form with your personal details, skills, interests, and availability 3) Submit the form and wait for our team to review your application 4) We will contact you within 3–5 business days to schedule an orientation session 5) Attend the orientation to learn about our mission and available opportunities 6) Start volunteering based on your schedule - you can serve monthly or weekly 7) After completing 20 hours of service, you will receive an official volunteer certificate. Volunteers aged 16+ are welcome (minors need parental consent). No prior experience is necessary as we provide all necessary training and support.', tokens: ['join','volunteer','apply','application','form','age','consent','orientation','contact','days','hours','certificate','availability','schedule','steps','personal','details','skills','interests','submit','review','mission','opportunities','training','support','experience'] },
  { id: 'apply-projects-events', url: '/projects', title: 'How to Apply for Events and Projects', content: 'To apply for events or projects with Wasilah, follow this process: 1) Open the Events or Projects page on our website 2) Browse through available opportunities and choose one that matches your interests and skills 3) Click the Apply or Register button for your selected opportunity 4) Fill in the application form with your background, motivation, and relevant experience 5) Submit your application and wait for confirmation 6) You will receive an email confirmation within 24 hours 7) Approved applicants will receive detailed logistics information and next steps via email 8) Attend the event or project as scheduled and make a positive impact in your community. If you need help selecting a project that matches your interests, you can contact us through the Contact page or use this chat widget for immediate assistance.', tokens: ['apply','applications','events','projects','register','opportunity','interests','motivation','confirmation','email','approved','logistics','steps','contact','help','process','browse','available','skills','background','experience','submit','detailed','information','scheduled','impact','community','assistance','immediate'] },
  { id: 'add-events-projects', url: '/dashboard', title: 'How to Add New Events and Projects (Admin)', content: 'Admins can add new events and projects via the Admin Panel. Open the Admin Panel from the header, go to Manage Events to add a new event with title, date, time, location, and description. For projects, navigate to the Submissions or Content sections to add or approve items. Approved submissions automatically become visible on the site.', tokens: ['admin','add','new','events','projects','manage','panel','title','date','time','location','description','approve','visible','site'] },
  { id: 'volunteer-requirements', url: '/volunteer', title: 'Volunteer Requirements and Benefits', content: 'Volunteer Requirements: Must be 16 years or older (parental consent required for minors), no prior experience necessary, commitment to attend orientation session, ability to communicate in English or Urdu, willingness to work in team environment. Benefits: Official volunteer certificate after 20 hours of service, skill development opportunities, networking with like-minded individuals, community impact and social responsibility, flexible scheduling options, training and mentorship support, recognition for outstanding contributions, opportunity to lead projects and initiatives, access to exclusive volunteer events and workshops, personal growth and character development.', tokens: ['volunteer','requirements','benefits','age','experience','orientation','communication','team','certificate','skill','development','networking','community','impact','scheduling','training','mentorship','recognition','leadership','exclusive','workshops','growth','character'] },
  { id: 'contact-information', url: '/contact', title: 'Contact Information and Office Locations', content: 'Wasilah Contact Information: Main Email: info@wasilah.org, Phone: +92-21-1234567 (Karachi), +92-42-1234567 (Lahore), +92-51-1234567 (Islamabad). Office Locations: Karachi Office - Main Office Complex, Clifton Block 5, Karachi (Monday-Friday, 9 AM-6 PM), Lahore Office - Model Town Extension, Lahore (Monday-Friday, 9 AM-6 PM), Islamabad Office - Blue Area Sector F-6, Islamabad (Monday-Friday, 9 AM-6 PM). Social Media: Facebook - @WasilahOfficial, Instagram - @wasilah_org, Twitter - @WasilahOrg. Response Time: Email responses within 24 hours on business days, Chat widget for immediate assistance, Phone calls answered during office hours. Emergency Contact: For urgent matters, call our main office numbers during business hours.', tokens: ['contact','information','office','locations','email','phone','karachi','lahore','islamabad','address','hours','social','media','facebook','instagram','twitter','response','time','emergency','urgent','business'] },
  { id: 'current-projects', url: '/projects', title: 'Current Projects and Initiatives', content: 'Current Wasilah Projects: 1) Education Initiative - Providing free tutoring and educational resources to underprivileged students, scholarship programs for deserving candidates, digital literacy workshops for youth and adults. 2) Healthcare Program - Free medical camps in underserved communities, health awareness campaigns on preventive care, mobile clinic services for remote areas. 3) Environmental Conservation - Tree planting drives across major cities, beach and river cleanup campaigns, sustainability workshops and eco-friendly practices education. 4) Community Development - Skills training programs for women and youth, livelihood support through micro-enterprise development, infrastructure improvement projects in rural areas. 5) Emergency Relief - Disaster response and relief operations, emergency food and shelter distribution, community resilience building programs. All projects are community-driven and designed for sustainable impact.', tokens: ['current','projects','initiatives','education','tutoring','resources','scholarship','digital','literacy','healthcare','medical','camps','awareness','preventive','mobile','clinic','environmental','conservation','tree','planting','beach','cleanup','sustainability','community','development','skills','training','livelihood','micro','enterprise','infrastructure','emergency','relief','disaster','response','food','shelter','resilience','sustainable','impact'] },
  { id: 'upcoming-events', url: '/events', title: 'Upcoming Events and Activities', content: 'Upcoming Wasilah Events: Monthly Health Fair (First Saturday of each month) - Free medical checkups, blood pressure and diabetes screening, health consultations with qualified doctors, free medicines for basic ailments. Educational Workshop Series (Every other Sunday) - Digital skills training, English language classes, career counseling sessions, resume writing workshops. Environmental Action Days (Third Saturday monthly) - Tree planting in designated areas, beach cleanup at Clifton Beach, river cleanup along Karachi coastline, environmental awareness sessions. Community Cultural Exchange (Last Friday of each month) - Cultural performances, traditional food stalls, community art exhibitions, interfaith dialogue sessions. Volunteer Appreciation Events (Quarterly) - Recognition ceremonies for outstanding volunteers, team building activities, networking opportunities, skill sharing sessions. All events are free to attend and open to the public. Registration required for workshops and limited-capacity events.', tokens: ['upcoming','events','activities','monthly','health','fair','medical','checkups','screening','consultations','doctors','medicines','educational','workshop','series','digital','skills','english','language','career','counseling','resume','writing','environmental','action','days','tree','planting','beach','cleanup','river','coastline','awareness','community','cultural','exchange','performances','traditional','food','stalls','art','exhibitions','interfaith','dialogue','volunteer','appreciation','recognition','ceremonies','team','building','networking','skill','sharing','free','attend','public','registration','required','limited','capacity'] }
];

export async function seedKnowledgeBase() {
  const results: { success: string[]; failed: Array<{ title: string; error: string }> } = { success: [], failed: [] };
  for (const page of INITIAL_KB_CONTENT) {
    try {
      const docRef = doc(db, 'kb', 'pages', 'content', page.id);
      await setDoc(docRef, { ...page, lastUpdated: serverTimestamp(), source: 'admin-enable' });
      results.success.push(page.title);
    } catch (e: any) {
      results.failed.push({ title: page.title, error: e?.message || 'unknown error' });
    }
  }
  return results;
}
